name: HFUTSCNetworkStudy

on:
  schedule:
    - cron: "00 1 * * *"
  watch:
    types: [ started ]


jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run checkin
        run: |
          python3 checkin.py --key_session ${{ secrets.KEY_SESSION }} --secret ${{ secrets.SECRET }}
      - name: Keep alive
        uses: gautamkrishnar/keepalive-workflow@v1